version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging: { driver: none }

  broker:
    #build: ./broker/
    image: confluentinc/cp-enterprise-kafka:5.1.2
    ports:
    - 9092:9092
    - 9011:9011
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PUBLIC://0.0.0.0:9092,INTERNAL://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "PUBLIC://localhost:9092,INTERNAL://broker:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PUBLIC:PLAINTEXT,INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 10
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"

      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "true"
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "broker:9092"
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: "1"
      #KAFKA_CONFLUENT_SUPPORT_METRICS_TOPIC: "__confluent.support.metrics"
      #KAFKA_CONFLUENT_SUPPORT_METRICS_ENDPOINT_INSECURE_ENABLE: "false"
      #KAFKA_CONFLUENT_SUPPORT_METRICS_ENDPOINT_SECURE_ENABLE: "false"
      #KAFKA_CONFLUENT_SUPPORT_METRICS_REPORT_INTERVAL_HOURS: "1"

      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: kafka.request.logger=TRACE
      #KAFKA_PRINCIPAL_BUILDER_CLASS: "com.nordstrom.kafka.security.auth.RegexPrincipalBuilder"
      # Regex to derive principal following 'slash-path' naming convention of <principal>/<uid>
      KAFKA_PRINCIPAL_BUILDER_REGEX: "(.+)/.+"
      # Uncomment to debug authorization.
      # KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=DEBUG,com.nordstrom.kafka.security.auth=DEBUG"
    depends_on: [zookeeper]
