#!/usr/bin/env bash

TOPIC=$1

AK="sgtpepper"
SK="lonelyheartsclubband"
BS=$pondBS

#needed to enable monitoring tools (jconsole, visualvm, etc)
#OPTS="-Djava.rmi.server.hostname=127.0.0.1"
java $OPTS -jar build/libs/kcr.jar --bootstrap-servers $BS --security-protocol SASL_SSL --sasl-mechanism SCRAM-SHA-512 --sasl-username $AK --sasl-password $SK record --topic $TOPIC --data-directory "confluent-5.2.2"
