#!/usr/bin/env bash

TOPIC=$1
CASSETTE=$2

#needed to enable monitoring tools (jconsole, visualvm, etc)
OPTS="-Djava.rmi.server.hostname=127.0.0.1"
java $OPTS -jar build/libs/kcr-all.jar play --cassette $CASSETTE --topic $TOPIC
